### ISSUE TITLE
Suggestion: Generate a hoogle database

### ISSUE THREAD

**Issue by chrisdone** [bitc/hdevtools#29]
Make a command like `generate-hoogle` for the given file and it would output a database for all top-level names. But not only that, _also_ all source spans. The source spans could be encoded in some trivial format of line_col_line_col, e.g.

``` haskell
Main_5_2_5_8 Char -> Int -> Bool
```

And when you query hoogle with `Char -> Int` you get back:

``` haskell
Main_5_2_5_8 :: Char -> Int -> Bool
```

Then Emacs, Vim, etc. could easily match that up with a region of the buffer of line 5 column 2 to line 5 column 8. Generating a hoogle database means hdevtools doesn't have to do any clever search stuff, it just needs to dump everything in the tree.

**Comment by bitc** [comment]
This seems like a really cool idea. Was this ever implemented in any Haskell tool?
