### ISSUE TITLE
hdevtools needs a new maintainer

### ISSUE THREAD

**Issue by schell** [bitc/hdevtools#44]
I'd like to pass on the maintainer's responsibilities - I don't have as much FOSS time as I used to. Are any of you guys interested? If so just let me know and I'll give you credentials :)

@maximkulkin
@dan-t
@ranjitjhala
@ch1bo
@parsonsmatt

**Comment by ch1bo** [comment]
I'll can do as I'm using hdevtools on a daily basis anyway. But, as you might have seen, I am not very experienced with maintaining open source projects :)

**Comment by ranjitjhala** [comment]
I'm happy to help too, since I use it a lot!
​

**Comment by schell** [comment]
Okay - I'll make a new official hdevtools github org, add us all as collaborators and then give you two maintainer credentials on hackage. Sound good?

Thank you! :)

**Comment by schell** [comment]
@ch1bo and @ranjitjhala can you guys tell me your hackage user names?

**Comment by parsonsmatt** [comment]
Unfortunately I also don't have much time to put towards this :(

Thanks for doing an excellent job maintaining the code @schell!

**Comment by ranjitjhala** [comment]
Indeed, thanks @schell!

I am ranjitjhala

On Mon, Nov 23, 2015 at 9:30 AM, Matt Parsons <notifications@github.com>
wrote:

> Unfortunately I also don't have much time to put towards this :(
>
> Thanks for doing an excellent job maintaining the code @schell
> <https://github.com/schell>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitc/hdevtools/issues/44#issuecomment-159004128>.
>



-- 
Ranjit.

**Comment by ch1bo** [comment]
Sounds like a plan!
Mine is ch1bo as well (just created it).

**Comment by schell** [comment]
Done and done :)
