### ISSUE TITLE
hdevtools check not working

### ISSUE THREAD

**Issue by schoettl** [bitc/hdevtools#45]
My current version of hdevtools does not work anymore:
```
$ hdevtools check ~/.xmonad/xmonad.hs

```
hangs or waits for input and can only be terminated with Ctrl-C (not with Ctrl-D).

This also breaks my Vim/Syntastic. Any ideas?

```
$ hdevtools --version
hdevtools: version 0.1.2.1 (ghc-7.10.2-x86_64-linux, cabal-1.22.4.0)
```

**Comment by schell** [comment]
@schoettl please use the new hdevtools org repo, https://github.com/hdevtools/hdevtools. This repo isn't listened to afaik :+1:

**Comment by schoettl** [comment]
Thank you, schell. I submitted an issue there.
