### ISSUE TITLE
Happy/Alex support

### ISSUE THREAD

**Issue by madgen** [bitc/hdevtools#47]
Firstly, this project saves me so much time on a daily basis, so thanks to everyone involved in developing and maintaining it.

I was wondering if there were plans to expand its functionality to Alex and/or Happy files?

Thanks!

**Comment by schell** [comment]
Madgen - thanks for your interest. You should check out the new project location at https://github.com/hdevtools/hdevtools.

**Comment by madgen** [comment]
Apologies. Thanks for all your hard work again.
